### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by aorzh**
Regarding this issue I did some changes for Python 3 support. Tested locally with Python 3.5.1 - working fine.

### CODE REVIEW

**Comment by redapple** [comment]
Thanks @aorzh !
We usually prefer Python 2 and Python 3 compatible code.
We've used [`six`](https://pythonhosted.org/six/) compatibility library to help with this in many of scrapy's or Scrapinghub's projects.
Could you work on a single Py2/Py3 codebase?

**Comment by aorzh** [comment]
Hi, thanks for the response, @redapple!  
Of course I can. Will provide correct pull request as soon as possible (but not asap - a bit busy).

**Comment by pawelmhm** [comment]
yeah we'll need code that work for 2 and 3, related PR #49

**Comment by pawelmhm** [comment]
closing #49 added Python 3 support 

Thanks for encouraging us to do this @aorzh

**Pull request closed without merging**
