### PR TITLE
SYS-1818: Enabled pypi deploy

### PR DESCRIPTION
**Pull request by cyberplant**

### CODE REVIEW

**Comment by cyberplant** [comment]
I've set it to deploy only on tags pushing. Do you want me to change that?

**Comment by chekunkov** [comment]
@cyberplant thanks for the PR, could you please add the following condition to the deploy: on: section:

```
deploy:
  on:
    condition: $TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$
```

**Comment by cyberplant** [comment]
Done!

**Comment by chekunkov** [comment]
Thanks @cyberplant

**Pull request merged**
