### PR TITLE
Test with Python 3.6

### PR DESCRIPTION
**Pull request by chekunkov**

### CODE REVIEW

**Comment by redapple** [comment]
@chekunkov , what do you think of using the latest scrapy on 1.0.x branch instead of 1.0.0? (something like `scrapy<1.1`)

**Comment by chekunkov** [comment]
@redapple sounds good to me, done

**Comment by pawelmhm** [comment]
:+1:  @chekunkov if we would like users to take advantage of that we should release this to pypi. Without pypi official supported versions will still be 2.7 and 3.5, see here https://pypi.python.org/pypi/scrapyrt I think it would be good to release it because I'm not sure when we're planning next release after current set of changes

**Comment by pawelmhm** [comment]
it would be also good way of testing if releases via travis work fine

**Comment by chekunkov** [comment]
mmm... not sure that change in trove classifiers is a good reason to release new version. users on py 3.6 still can install scrapyrt from pypi without any problem, it's just that pypi page doesn't mention that. @redapple do you know what's the best practice here?

**Comment by redapple** [comment]
I think a 0.10.1 patch release would work fine here: it's a good way to test auto-deploys from Travis CI as @pawelmhm mentions, and also having wheels + src distributions is nice. That's what we did for [cssselect 1.0.1](https://cssselect.readthedocs.io/en/latest/#version-1-0-1) for example.

**Comment by chekunkov** [comment]
ok, let's do that

**Pull request merged**
